#!/usr/bin/env python3
USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/120.0.0.0 Safari/537.36',
]
SEC_CH_UA = [
    '"Chromium";v="120", "Google Chrome";v="120", "Not?A_Brand";v="99"',
    '"Chromium";v="122", "Google Chrome";v="122", "Not?A_Brand";v="99"',
    '"Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"',
    '"Microsoft Edge";v="120", "Chromium";v="120", "Not?A_Brand";v="99"',
    '"Firefox";v="121", "Firefox";v="121", "Not?A_Brand";v="8"',
    '"Safari";v="17.1", "Not?A_Brand";v="8", "Chromium";v="120"',
    '"Brave";v="120", "Chromium";v="120", "Not?A_Brand";v="99"',
    '"Opera";v="106", "Chromium";v="120", "Not?A_Brand";v="99"',
]
SEC_CH_UA_PLATFORM = [
    '"Windows"',
    '"macOS"',
    '"Linux"',
    '"Android"',
    '"iOS"',
    '"Chrome OS"',
    '"Chromium OS"',
    '"Ubuntu"',
]
CIPHER_SUITES = [
    'ECDHE-RSA-AES128-GCM-SHA256',
    'ECDHE-RSA-AES256-GCM-SHA384',
    'ECDHE-ECDSA-AES128-GCM-SHA256',
    'ECDHE-ECDSA-AES256-GCM-SHA384',
    'ECDHE-RSA-CHACHA20-POLY1305',
    'ECDHE-ECDSA-CHACHA20-POLY1305',
    'AES128-GCM-SHA256',
    'AES256-GCM-SHA384',
    'AES128-SHA256',
    'AES256-SHA256',
    'AES128-SHA',
    'AES256-SHA',
    'DES-CBC3-SHA',
    'TLS_AES_128_GCM_SHA256',
    'TLS_AES_256_GCM_SHA384',
    'TLS_CHACHA20_POLY1305_SHA256',
]
non_suspicious_keywords = [
    'not found', 'invalid', 'bad request', 'malformed', 'not exist', 'does not exist',
    'not available', 'not valid', 'missing', 'required', 'cannot be empty',
    'already exists', 'already taken', 'already used', 'duplicate', 
    'must be', 'should be', 'expected', 'unexpected',
    'unauthorized', 'forbidden', 'access denied', 'permission denied',
    'login failed', 'invalid credentials', 'wrong password', 'account locked',
    'session expired', 'csrf token invalid', 'csrf validation failed',
    'captcha', 'recaptcha', 'verification failed',
    'validation failed', 'validation error', 'format incorrect',
    'email format', 'phone number', 'zip code', 'postal code',
    'min length', 'max length', 'minimum', 'maximum', 'between',
    'alphanumeric', 'special characters', 'contains', 'pattern',
    'duplicate entry', 'unique constraint', 'foreign key',
    'cannot be null', 'not null', 'primary key', 'constraint violation',
    'out of stock', 'insufficient stock', 'insufficient balance',
    'expired', 'already used', 'already redeemed', 'already claimed',
    'minimum order', 'maximum order', 'limit exceeded',
    'tidak ditemukan', 'tidak valid', 'tidak tersedia',
    'tidak boleh kosong', 'harus diisi', 'wajib diisi',
    'sudah ada', 'sudah digunakan', 'sudah terdaftar',
    'gagal', 'kesalahan', 'error', 'salah',
    'username salah', 'password salah', 'email salah',
    'captcha salah', 'verifikasi gagal',
    '見つかりません', '存在しません', '無効です', '必須です',
    '既に存在します', '既に使用されています', '失敗しました',
    '未找到', '不存在', '无效', '必须填写', '不能为空',
    '已存在', '已使用', '失败', '错误',
    'non trouvé', 'invalide', 'requis', 'obligatoire',
    'existe déjà', 'déjà utilisé', 'échoué', 'erreur',
    'nicht gefunden', 'ungültig', 'erforderlich', 'pflichtfeld',
    'existiert bereits', 'bereits verwendet', 'fehlgeschlagen', 'fehler',
    'no encontrado', 'inválido', 'requerido', 'obligatorio',
    'ya existe', 'ya utilizado', 'falló', 'error',
    'غير موجود', 'غير صالح', 'مطلوب', 'موجود بالفعل',
    'не найден', 'недействителен', 'обязательно', 'уже существует',
    '404', '400', 'method not allowed', '405',
    'too many requests', '429', 'rate limit',
    'service unavailable', '503', 'maintenance',
    'bad gateway', '502', 'gateway timeout', '504'
]
error_patterns_contextual = [
    'undefinederror', 'templatesyntaxerror', 'templatenotfound',
    'templateerror', 'template runtime error', 'template compilation error',
    'undefined variable', 'unknown variable', 'unclosed tag',
    'unexpected closing', 'missing closing', 'invalid expression',
    'malformed template', 'bad template', 'template not found',
    'template does not exist', 'cannot find template',
    'failed to render', 'rendering error', 'execution error',
    'nullpointerexception', 'classcastexception', 'illegalargumentexception',
    'undefined method', 'uninitialized constant',
    'syntaxerror', 'nomethoderror', 'nameerror', 'typeerror', 'valueerror'
]
python_error_patterns = [
    'traceback', 'most recent call last', 'filenotfounderror', 'importerror',
    'indexerror', 'keyerror', 'valueerror', 'typeerror', 'nameerror',
    'attributeerror', 'zerodivisionerror', 'runtimeerror', 'notimplementederror',
    'jinja2.exceptions', 'jinja2', 'django.template', 'mako.exceptions',
    'cheetah.exception', 'chameleon.exc', 'genshi.error', 'bottle error',
    'flask error', 'werkzeug', 'tornado.error', 'web2py error',
    'undefinederror', 'templatesyntaxerror', 'templatenotfound',
    'templateerror', 'template runtime error', 'template compilation error'
]
php_error_patterns = [
    'twig_error', 'twig_', 'smarty', 'blade', 'laravel', 'latte\\',
    'raintpl', 'mustache.php', 'phalcon', 'volterror', 'dwoo',
    'fenom\\', 'phpbb_template', 'savant3', 'flexy', 'patemplate',
    'unexpected tag', 'unknown tag', 'unclosed tag', 'parse error',
    'syntax error, unexpected', 'compilation failed', 'template error in'
]
java_error_patterns = [
    'freemarker', 'freemarker.core', 'freemarker.template',
    'org.apache.velocity', 'velocityexception', 'thymeleaf',
    'pebble', 'jte', 'rocker', 'jstachio', 'manifold', 'htmlflow',
    'closure templates', 'soy', 'httl', 'beetl', 'enjoy', 'rythm',
    'javax.servlet.jsp', 'org.apache.jasper', 'facelets',
    'org.apache.tapestry', 'org.apache.wicket', 'jade4j', 'trimou',
    'com.github.jknack.handlebars', 'com.github.mustachejava',
    'com.hubspot.jinjava', 'scalate', 'play.templates',
    'groovy.text', 'org.jamon', 'nullpointerexception',
    'classcastexception', 'illegalargumentexception', 'stacktrace'
]
js_error_patterns = [
    'pug:', 'jade:', 'ejs:', 'handlebars:', 'mustache:',
    'nunjucks:', 'dot:', 'liquidjs:', 'marko:', 'hogan:',
    'haml:', 'slim:', 'eta:', 'art-template:', 'swig:',
    'dust:', 'ractive:', 'vue:', 'angular:', '_.template',
    'lodash template', 'jquery.tmpl', 'bracket template',
    'whiskers', 'plates.js', 't.js', 'templayed', 'json-template',
    'motemplate', 'scribe.js', 'template parse error',
    'unexpected token', 'missing closing', 'cannot read property'
]
ruby_error_patterns = [
    'erb', 'haml', 'slim', 'liquid', 'mustache.rb',
    'handlebars.rb', 'rabl', 'jbuilder', 'tilt',
    'curly', 'radius', 'markaby', 'erubis', 'tenjin', 'mab',
    'syntaxerror', 'nomethoderror', 'undefined method',
    'uninitialized constant', 'template error'
]
go_error_patterns = [
    'pongo2', 'jet', 'hero', 'quicktemplate', 'raymond', 'ego',
    'html/template', 'text/template', 'ace', 'amber',
    'mustache.go', 'handlebars.go', 'liquid.go',
    'template: ', 'executing template', 'parsing template',
    'undefined variable', 'unclosed action'
]
dotnet_error_patterns = [
    'razor', 'scriban', 'fluid', 'dotliquid', 'handlebars.net',
    'stubble', 'nustache', 'mustache#', 'spark', 'nhaml',
    'brail', 'sharptempl', 'liquid.net', 'system.web.razor',
    'razorlight', 'razorengine', 'microsoft.aspnetcore.razor',
    'cshtml', 'vbhtml', 'template compilation', 'template rendering'
]
cpp_error_patterns = [
    'inja', 'jinja2cpp', 'mstch', 'qentem', 'teng::',
    'ctemplate', 'mustache.cpp', 'fmt::', 'pugic', 'kainjow',
    'template error', 'rendering error', 'parsing error'
]
perl_error_patterns = [
    'template toolkit', 'template::', 'mason', 'html::template',
    'text::template', 'template::perl', 'template::stash',
    'template exception', 'template error'
]
common_error_patterns = [
    'exception', 'error on line', 'runtimeerror', 'compile error',
    'compilation error', 'parsing error', 'syntax error',
    'template error', 'undefined variable', 'unknown variable',
    'unclosed tag', 'unexpected closing', 'missing closing',
    'invalid expression', 'malformed template', 'bad template',
    'template not found', 'template does not exist', 'cannot find template',
    'failed to render', 'rendering error', 'execution error',
    'stack trace', 'stacktrace', 'at ', 'in ', 'line ',
    'server error', 'internal server error', '500',
    'runtime exception', 'fatal error', 'unhandled exception'
]
all_error_patterns = [
    'Traceback', 'SyntaxError', 'NameError', 'TypeError', 'ValueError',
    'jinja2', 'django', 'mako', 'cheetah', 'chameleon', 'genshi',
    'flask', 'werkzeug', 'tornado', 'web2py',
    'twig', 'smarty', 'blade', 'laravel', 'latte', 'raintpl',
    'phalcon', 'volt', 'dwoo', 'fenom',
    'freemarker', 'velocity', 'thymeleaf', 'pebble', 'jte',
    'rocker', 'jstachio', 'manifold', 'htmlflow', 'closure',
    'soy', 'httl', 'beetl', 'enjoy', 'rythm', 'jsp', 'facelets',
    'tapestry', 'wicket', 'jade4j', 'trimou', 'handlebars.java',
    'mustache.java', 'jinjava', 'scalate', 'play', 'groovy',
    'jamon', 'knight', 'spring', 'org.springframework',
    'pug', 'jade', 'ejs', 'handlebars', 'mustache', 'nunjucks',
    'dot', 'liquidjs', 'marko', 'hogan', 'haml', 'slim', 'eta',
    'art-template', 'swig', 'dust', 'ractive', 'vue', 'angular',
    'underscore', 'lodash', 'jquery.tmpl',
    'erb', 'haml', 'slim', 'liquid', 'rabl', 'jbuilder', 'tilt',
    'curly', 'radius', 'markaby', 'erubis', 'tenjin', 'mab',
    'pongo2', 'jet', 'hero', 'quicktemplate', 'raymond', 'ego',
    'ace', 'amber',
    'razor', 'scriban', 'fluid', 'dotliquid', 'handlebars.net',
    'stubble', 'nustache', 'spark', 'nhaml', 'brail',
    'asp.net', 'ASP.NET', 'System.Web', 'System.Web.UI',
    'inja', 'jinja2cpp', 'mstch', 'qentem', 'ctemplate',
    'template toolkit', 'mason',
    'exception', 'error on line', 'runtimeerror',
    'compilation error', 'template error', 'undefined variable',
    'unclosed tag', 'unexpected', 'malformed', 'invalid expression'
]
engine_signatures = {
    'jinja2': ['jinja2', 'jinja2.exceptions', 'jinja2.exceptions.UndefinedError', 'jinja2.exceptions.TemplateSyntaxError', 'jinja2.exceptions.TemplateNotFound', 'jinja2.Template', 'jinja2.Environment'],
    'django': ['django', 'django.template', 'django.template.exceptions', 'django.template.exceptions.TemplateSyntaxError', 'django.template.exceptions.TemplateDoesNotExist', 'django.template.base', 'django.template.loader', 'django.template.context'],
    'mako': ['mako', 'mako.exceptions', 'MakoException', 'mako.runtime', 'mako.template', 'mako.lookup', 'mako.exceptions.RichTraceback'],
    'cheetah': ['cheetah', 'Cheetah.Template', 'Cheetah.NameMapper', 'cheetah.compile', 'CheetahException', 'Cheetah.Template.Template'],
    'teng': ['teng', 'TEng', 'template engine teng', 'TEng library', 'teng::Template'],
    'chameleon': ['chameleon', 'chameleon.zpt', 'chameleon.tales', 'chameleon.exc', 'chameleon.template', 'chameleon.compiler'],
    'genshi': ['genshi', 'GenshiError', 'genshi.template', 'genshi.filters', 'genshi.core', 'genshi.template.markup'],
    'stringtemplate': ['stringtemplate', 'StringTemplate', 'STGroup', 'NoSuchAttributeException', 'org.antlr.stringtemplate'],
    'jinjava': ['jinjava', 'Jinjava', 'com.hubspot.jinjava', 'jinjava.objects'],
    'pyratemp': ['pyratemp', 'pyratemp.Template', 'pyratemp.parser'],
    'spitfire': ['spitfire', 'Spitfire', 'spitfire.compiler'],
    'bottle': ['bottle', 'Bottle', 'bottle.template', 'bottle.Template', 'bottle.SimpleTemplate'],
    'flask': ['flask', 'Flask', 'werkzeug', 'Werkzeug', 'flask.templating'],
    'tornado': ['tornado', 'Tornado', 'tornado.template', 'tornado.escape'],
    'web2py': ['web2py', 'web2py.gluon', 'gluon.template'],
    'quik': ['quik', 'Quik', 'quik.Template'],
    'pystache': ['pystache', 'Pystache', 'pystache.renderer'],
    'pybars': ['pybars', 'Pybars', 'pybars.Compiler'],
    'pystringtemplate': ['pystringtemplate', 'PyStringTemplate'],
    'twig': ['twig', 'Twig_Error', 'Twig_Error_Syntax', 'Twig_Error_Runtime', 'Twig_Error_Loader', 'Twig_Template', 'Twig_Environment', 'Twig_Extension', 'Twig_Loader'],
    'smarty': ['smarty', 'SmartyException', 'SmartyCompilerException', 'SmartyTemplate', 'smarty_internal', 'Smarty_Internal_Template', 'Smarty_Internal_Compile'],
    'blade': ['blade', 'Blade', 'laravel', 'Illuminate.View', 'Illuminate.View.Engine.CompilerEngine', 'Illuminate.View.Compilers.BladeCompiler'],
    'latte': ['latte', 'Latte', 'Latte\\CompileException', 'Latte\\RuntimeException', 'Latte\\Engine', 'Latte\\Macros'],
    'raintpl': ['raintpl', 'RainTPL', 'raintpl3', 'RainTpl', 'Rain.Tpl'],
    'mustache.php': ['mustache.php', 'Mustache_Engine', 'Mustache_Exception', 'Mustache_Template'],
    'plates': ['plates', 'Plates', 'League\\Plates', 'Plates\\Engine'],
    'volt': ['volt', 'Volt', 'Phalcon\\Mvc\\View\\Engine\\Volt', 'Phalcon_Mvc_View_Engine_Volt'],
    'haml.php': ['haml.php', 'HamlPHP', 'Haml\\Haml'],
    'dwoo': ['dwoo', 'Dwoo', 'Dwoo_Template', 'Dwoo_Compiler'],
    'fenom': ['fenom', 'Fenom', 'Fenom\\Template'],
    'tpl': ['tpl', 'Tpl', 'Tpl\\Template'],
    'phpbb': ['phpbb', 'phpBB', 'phpbb_template'],
    'savant': ['savant', 'Savant3', 'Savant3_Plugin'],
    'flexy': ['flexy', 'Flexy', 'HTML_Flexy'],
    'patemplate': ['patemplate', 'PATemplate', 'patTemplate'],
    'freemarker': ['freemarker', 'freemarker.core', 'freemarker.template', 'freemarker.core.InvalidReferenceException', 'freemarker.template.TemplateException', 'freemarker.template.TemplateModelException', 'freemarker.template.TemplateNotFoundException', 'freemarker.ext.servlet'],
    'velocity': ['velocity', 'org.apache.velocity', 'VelocityException', 'org.apache.velocity.exception', 'org.apache.velocity.exception.ParseErrorException', 'org.apache.velocity.exception.ResourceNotFoundException', 'org.apache.velocity.context', 'org.apache.velocity.app'],
    'thymeleaf': ['thymeleaf', 'Thymeleaf', 'org.thymeleaf', 'thymeleaf.spring', 'thymeleaf.exceptions', 'thymeleaf.TemplateEngine', 'org.thymeleaf.templateresolver'],
    'pebble': ['pebble', 'Pebble', 'com.mitchellbosecke.pebble', 'PebbleException', 'com.mitchellbosecke.pebble.template'],
    'jte': ['jte', 'JTE', 'gg.jte', 'jte.TemplateEngine', 'gg.jte.html'],
    'rocker': ['rocker', 'Rocker', 'com.fizzed.rocker', 'rocker.Template', 'RockerTemplate'],
    'pug4j': ['pug4j', 'Pug4J', 'de.neuland.pug4j', 'pug4j.PugConfiguration'],
    'jstachio': ['jstachio', 'JStachio', 'io.jstach.jstachio'],
    'manifold': ['manifold', 'ManTL', 'systems.manifold', 'manifold.templates'],
    'htmlflow': ['htmlflow', 'HtmlFlow', 'htmlflow.HtmlFlow', 'HtmlFlowException'],
    'closure-templates': ['closure-templates', 'Closure Templates', 'com.google.template.soy', 'soy', 'SoyTemplate', 'SoyFileSet'],
    'httl': ['httl', 'HTTL', 'httl.spi', 'httl.Template', 'httl.Engine'],
    'beetl': ['beetl', 'BeetlTemplate', 'beetl.core', 'org.beetl.ext', 'beetl.GroupTemplate'],
    'enjoy': ['enjoy', 'Enjoy Template', 'com.jfinal.template', 'jfinal.template'],
    'rythm': ['rythm', 'Rythm', 'org.rythmengine', 'rythm.RythmEngine'],
    'jsp': ['jsp', 'JSP', 'javax.servlet.jsp', 'org.apache.jasper', 'org.apache.jasper.runtime'],
    'facelets': ['facelets', 'Facelets', 'javax.faces.view', 'com.sun.facelets'],
    'tapestry': ['tapestry', 'Tapestry', 'org.apache.tapestry', 'org.apache.tapestry5'],
    'wicket': ['wicket', 'Wicket', 'org.apache.wicket', 'wicket.markup'],
    'jade4j': ['jade4j', 'Jade4J', 'de.neuland.jade4j'],
    'trimou': ['trimou', 'Trimou', 'org.trimou', 'trimou.engine'],
    'handlebars.java': ['handlebars.java', 'Handlebars.java', 'com.github.jknack.handlebars'],
    'mustache.java': ['mustache.java', 'Mustache.java', 'com.github.mustachejava'],
    'jinja2.java': ['jinja2.java', 'Jinja2.java', 'com.hubspot.jinjava'],
    'scalate': ['scalate', 'Scalate', 'org.fusesource.scalate', 'scalate.TemplateEngine'],
    'play.templates': ['play.templates', 'Play!', 'play.templates.Template'],
    'groovy.template': ['groovy.template', 'GroovyTemplate', 'groovy.text'],
    'jamon': ['jamon', 'Jamon', 'org.jamon'],
    'knight': ['knight', 'Knight', 'com.knight.template'],
    'pug': ['pug', 'Pug', 'pug.js', 'jade', 'Jade', 'pug.compile', 'pug.render'],
    'ejs': ['ejs', 'EJS', 'ejs.js', 'ejs:', 'ejs.compile', 'ejs.render', 'ejs.Template'],
    'handlebars': ['handlebars', 'Handlebars', 'handlebars.js', 'Handlebars.SafeString', 'Handlebars.compile', 'Handlebars.template', 'handlebars/dist/cjs/handlebars', 'Handlebars.parse', 'handlebars/compiler/parser'],
    'mustache': ['mustache', 'Mustache', 'mustache.js', 'Mustache.render', 'mustache.to_html'],
    'nunjucks': ['nunjucks', 'Nunjucks', 'nunjucks.Environment', 'nunjucks.Template', 'nunjucks.compile', 'nunjucks.render'],
    'dot': ['doT', 'doT.js', 'dot.template', 'doT.compile', 'dot.process'],
    'liquidjs': ['liquidjs', 'LiquidJS', 'liquidjs.engine', 'liquidjs.Liquid', 'liquidjs.Template'],
    'marko': ['marko', 'Marko', 'marko-js', 'marko.compile', 'marko.render', 'marko.Template'],
    'hogan.js': ['hogan.js', 'Hogan', 'hogan.Template', 'hogan.compile', 'hogan.render'],
    'haml': ['haml', 'HAML', 'haml-js', 'haml.compile', 'haml.render'],
    'slim': ['slim', 'Slim', 'slim-lang', 'slim.js'],
    'eta': ['eta', 'Eta', 'eta.js', 'eta.compile', 'eta.render'],
    'art-template': ['art-template', 'artTemplate', 'template.compile', 'template.render'],
    'swig': ['swig', 'Swig', 'swig.js', 'swig.compile', 'swig.render', 'swig.Template'],
    'dust': ['dust', 'Dust', 'dustjs', 'dust.compile', 'dust.render', 'dust.Template'],
    'ractive': ['ractive', 'Ractive', 'ractive.js', 'ractive.parse', 'ractive.template'],
    'vue': ['vue', 'Vue', 'vue.js', 'vue-template', 'vue.compile', 'vue.render'],
    'angular': ['angular', 'Angular', 'angular.js', 'ng-template', 'angular.compile'],
    'microtemplate': ['microtemplate', 'MicroTemplate', '_.template'],
    'underscore': ['underscore', 'Underscore', '_.template'],
    'lodash': ['lodash', 'Lodash', '_.template'],
    'jquery-tmpl': ['jquery-tmpl', 'jQuery.tmpl', 'jquery.template'],
    'mustache-hogan': ['mustache-hogan', 'hogan.mustache'],
    'bracket': ['bracket', 'Bracket', 'bracket-template'],
    'whiskers': ['whiskers', 'Whiskers', 'whiskers.js'],
    'plates': ['plates', 'Plates.js', 'plates.Template'],
    't': ['t.js', 't.Template', 't.render'],
    'templayed': ['templayed', 'Templayed', 'templayed.js'],
    'json-template': ['json-template', 'JSONTemplate'],
    'motemplate': ['motemplate', 'MOTemplate'],
    'scribe': ['scribe', 'Scribe.js'],
    'erb': ['erb', 'ERB', 'eRuby', 'ruby', 'ERB.new', 'ERB.result'],
    'haml': ['haml', 'HAML', 'haml-rails', 'Haml::Engine', 'Haml::Template'],
    'slim': ['slim', 'Slim', 'slim-lang', 'Slim::Template', 'Slim::Engine'],
    'liquid': ['liquid', 'Liquid', 'Liquid::Template', 'Liquid::Variable', 'Liquid::Tag'],
    'mustache.rb': ['mustache.rb', 'Mustache', 'Mustache::Template'],
    'handlebars.rb': ['handlebars.rb', 'Handlebars.rb', 'Handlebars::Template'],
    'rabl': ['rabl', 'RABL', 'Rabl::Template'],
    'jbuilder': ['jbuilder', 'Jbuilder', 'JbuilderTemplate'],
    'tilt': ['tilt', 'Tilt', 'Tilt::Template'],
    'curly': ['curly', 'Curly', 'Curly::Template'],
    'radius': ['radius', 'Radius', 'Radius::Template'],
    'markaby': ['markaby', 'Markaby', 'Markaby::Template'],
    'erubis': ['erubis', 'Erubis', 'Erubis::Eruby'],
    'tenjin': ['tenjin', 'Tenjin', 'Tenjin::Template'],
    'mab': ['mab', 'Mab', 'Mab::Template'],
    'pongo2': ['pongo2', 'Pongo2', 'pongo2.Template', 'pongo2.Context', 'pongo2.Render'],
    'jet': ['jet', 'Jet', 'jet.Template', 'jet.Set', 'jet.Runtime'],
    'hero': ['hero', 'Hero', 'hero.Template', 'hero.Render'],
    'quicktemplate': ['quicktemplate', 'QuickTemplate', 'quicktemplate.qt', 'qtpl'],
    'raymond': ['raymond', 'Raymond', 'raymond.Raymond', 'raymond.Parse'],
    'ego': ['ego', 'Ego', 'ego.Template', 'ego.Execute'],
    'templates': ['templates', 'html/template', 'text/template', 'template.Template'],
    'ace': ['ace', 'Ace', 'ace.Template', 'ace.compile', 'ace.render'],
    'amber': ['amber', 'Amber', 'amber.Template'],
    'mustache.go': ['mustache.go', 'Mustache.go', 'mustache.Render'],
    'handlebars.go': ['handlebars.go', 'Handlebars.go', 'handlebars.Render'],
    'liquid.go': ['liquid.go', 'Liquid.go', 'liquid.Template'],
    'razor': ['razor', 'Razor', 'System.Web.Razor', 'RazorLight', 'RazorEngine', 'RazorView', 'Microsoft.AspNetCore.Razor'],
    'scriban': ['scriban', 'Scriban', 'scriban.Template', 'Scriban.TemplateContext', 'scriban.parser'],
    'fluid': ['fluid', 'Fluid', 'FluidTemplate', 'FluidParser', 'FluidTemplateParser'],
    'dotliquid': ['dotliquid', 'DotLiquid', 'DotLiquid.Template', 'DotLiquid.Context', 'DotLiquid.Hash'],
    'handlebars.net': ['handlebars.net', 'Handlebars.Net', 'HandlebarsTemplate', 'Handlebars.Compiler'],
    'stubble': ['stubble', 'Stubble', 'Stubble.Template', 'Stubble.Compilation'],
    'nustache': ['nustache', 'Nustache', 'Nustache.Core'],
    'mustache.sharp': ['mustache.sharp', 'MustacheSharp'],
    'spark': ['spark', 'Spark', 'SparkView', 'SparkEngine'],
    'nhaml': ['nhaml', 'NHaml', 'NHaml.Template'],
    'brail': ['brail', 'Brail', 'BrailTemplate'],
    'sharp_templ': ['sharp_templ', 'SharpTempl'],
    'liquid.net': ['liquid.net', 'Liquid.NET'],
    'inja': ['inja', 'Inja', 'inja.Template', 'inja.Environment', 'inja.Render'],
    'jinja2cpp': ['jinja2cpp', 'Jinja2Cpp', 'jinja2::Template', 'jinja2::Environment'],
    'mstch': ['mstch', 'mstch', 'mstch::template', 'mstch::context'],
    'qentem': ['qentem', 'Qentem', 'qentem.Template', 'Qentem::Template'],
    'teng_cpp': ['teng', 'TEng', 'teng::Template', 'teng::Engine'],
    'ctemplate': ['ctemplate', 'Ctemplate', 'ctemplate.Template', 'google.template'],
    'mustache.cpp': ['mustache.cpp', 'Mustache.cpp', 'mustache::Render'],
    'fmt': ['fmt', 'FMT', 'fmt::format', 'fmt::printf'],
    'pugic': ['pugic', 'Pugic'],
    'kainjow': ['kainjow', 'Kainjow', 'mustache'],
    'template-toolkit': ['template toolkit', 'Template::Toolkit', 'perl', 'Template.pm', 'Template::Exception', 'Template::Context'],
    'mason': ['mason', 'HTML::Mason', 'Mason', 'HTML::Mason::Interp', 'Mason::Interp'],
    'html-template': ['html-template', 'HTML::Template', 'HTML.Template'],
    'text-template': ['text-template', 'Text::Template', 'Text.Template'],
    'template-perl': ['template-perl', 'Template::Perl'],
    'template-stash': ['template-stash', 'Template::Stash'],
    'open-power-template': ['open power template', 'OPT', 'OPTv2', 'OpenPowerTemplate'],
    'apache-tapestry': ['tapestry', 'Tapestry', 'org.apache.tapestry'],
    'velocity-tools': ['velocity-tools', 'VelocityTools', 'org.apache.velocity.tools'],
    'gsp': ['gsp', 'GSP', 'groovy.server.pages', 'GroovyPages'],
    'ssp': ['ssp', 'SSP', 'Scala Server Pages'],
    'jtwig': ['jtwig', 'JTwig', 'jtwig.Template', 'jtwig.parser'],
    'jinjava': ['jinjava', 'Jinjava', 'com.hubspot.jinjava'],
    'chunk': ['chunk', 'Chunk', 'chunk.template'],
    'tnt': ['tnt', 'TnT', 'tnt.template'],
    'stringloader': ['stringloader', 'StringLoader'],
    'phptal': ['phptal', 'PHPTAL', 'PHPTAL_Template'],
    'django-jinja': ['django-jinja', 'DjangoJinja'],
    'coffee': ['coffee', 'CoffeeKup', 'coffeekup'],
    'dry': ['dry', 'Dry', 'dry.template'],
    'walrus': ['walrus', 'Walrus', 'walrus.template'],
    'sqwig': ['sqwig', 'Sqwig'],
    'hogan': ['hogan', 'Hogan.js'],
    'mu2': ['mu2', 'Mu2', 'mu2.compile'],
    'templayed': ['templayed', 'Templayed.js'],
    'underscore': ['underscore', 'Underscore.js'],
    'spacebars': ['spacebars', 'Spacebars', 'meteor.spacebars'],
    'blaze': ['blaze', 'Blaze', 'meteor.blaze'],
    'handlebars-objc': ['handlebars-objc', 'Handlebars.objc'],
    'grust': ['grust', 'Grust', 'grust.template'],
    'templ8': ['templ8', 'Templ8'],
    'tempest': ['tempest', 'Tempest', 'tempest.template'],
    'plates': ['plates', 'Plates', 'plates.Template'],
    'soy': ['soy', 'Closure Templates', 'soy.Template']
}
high_priority_patterns = {
    'jinja2': [r'jinja2[\\/]', r'jinja2\.exceptions\.\w+Error', r'jinja2\.environment'],
    'django': [r'django[\\/]template', r'django\.template\.exceptions\.\w+Error'],
    'mako': [r'mako[\\/]', r'mako\.exceptions\.\w+Exception'],
    'cheetah': [r'cheetah[\\/]', r'Cheetah\.Template'],
    'teng': [r'teng[\\/]', r'teng::Template'],
    'chameleon': [r'chameleon[\\/]', r'chameleon\.exceptions'],
    'genshi': [r'genshi[\\/]', r'genshi\.template'],
    'stringtemplate': [r'stringtemplate[\\/]', r'StringTemplate', r'STGroup'],
    'jinjava': [r'jinjava[\\/]', r'com\.hubspot\.jinjava'],
    'pyratemp': [r'pyratemp[\\/]', r'pyratemp\.Template'],
    'spitfire': [r'spitfire[\\/]', r'spitfire\.compiler'],
    'bottle': [r'bottle[\\/]', r'bottle\.template'],
    'flask': [r'flask[\\/]', r'flask\.templating'],
    'tornado': [r'tornado[\\/]', r'tornado\.template'],
    'web2py': [r'web2py[\\/]', r'gluon\.template'],
    'quik': [r'quik[\\/]', r'quik\.Template'],
    'pystache': [r'pystache[\\/]', r'pystache\.renderer'],
    'pybars': [r'pybars[\\/]', r'pybars\.Compiler'],
    'pystringtemplate': [r'pystringtemplate[\\/]', r'PyStringTemplate'],
    'twig': [r'twig[\\/]', r'Twig_Error_\w+', r'Twig_Environment'],
    'smarty': [r'smarty[\\/]', r'SmartyException', r'Smarty_Internal_Template'],
    'blade': [r'blade[\\/]', r'Illuminate\\View', r'BladeCompiler'],
    'latte': [r'latte[\\/]', r'Latte\\CompileException', r'Latte\\Engine'],
    'raintpl': [r'raintpl[\\/]', r'RainTPL', r'Rain\.Tpl'],
    'mustache.php': [r'mustache\.php[\\/]', r'Mustache_Engine'],
    'plates': [r'plates[\\/]', r'League\\Plates'],
    'volt': [r'volt[\\/]', r'Phalcon\\Mvc\\View\\Engine\\Volt'],
    'haml.php': [r'haml\.php[\\/]', r'HamlPHP'],
    'dwoo': [r'dwoo[\\/]', r'Dwoo_Template'],
    'fenom': [r'fenom[\\/]', r'Fenom\\Template'],
    'tpl': [r'tpl[\\/]', r'Tpl\\Template'],
    'phpbb': [r'phpbb[\\/]', r'phpbb_template'],
    'savant': [r'savant[\\/]', r'Savant3'],
    'flexy': [r'flexy[\\/]', r'HTML_Flexy'],
    'patemplate': [r'patemplate[\\/]', r'patTemplate'],
    'freemarker': [r'freemarker[\\/]', r'freemarker\.core\.\w+Exception', r'freemarker\.template'],
    'velocity': [r'velocity[\\/]', r'org\.apache\.velocity\.\w+Exception'],
    'thymeleaf': [r'thymeleaf[\\/]', r'org\.thymeleaf', r'thymeleaf\.exceptions'],
    'pebble': [r'pebble[\\/]', r'com\.mitchellbosecke\.pebble', r'PebbleException'],
    'jte': [r'jte[\\/]', r'gg\.jte', r'jte\.TemplateEngine'],
    'rocker': [r'rocker[\\/]', r'com\.fizzed\.rocker'],
    'pug4j': [r'pug4j[\\/]', r'de\.neuland\.pug4j'],
    'jstachio': [r'jstachio[\\/]', r'io\.jstach\.jstachio'],
    'manifold': [r'manifold[\\/]', r'systems\.manifold'],
    'htmlflow': [r'htmlflow[\\/]', r'htmlflow\.HtmlFlow'],
    'closure-templates': [r'closure-templates[\\/]', r'com\.google\.template\.soy'],
    'httl': [r'httl[\\/]', r'httl\.Template', r'httl\.Engine'],
    'beetl': [r'beetl[\\/]', r'org\.beetl\.ext', r'beetl\.GroupTemplate'],
    'enjoy': [r'enjoy[\\/]', r'com\.jfinal\.template'],
    'rythm': [r'rythm[\\/]', r'org\.rythmengine', r'rythm\.RythmEngine'],
    'jsp': [r'jsp[\\/]', r'javax\.servlet\.jsp', r'org\.apache\.jasper'],
    'facelets': [r'facelets[\\/]', r'javax\.faces\.view'],
    'tapestry': [r'tapestry[\\/]', r'org\.apache\.tapestry'],
    'wicket': [r'wicket[\\/]', r'org\.apache\.wicket'],
    'jade4j': [r'jade4j[\\/]', r'de\.neuland\.jade4j'],
    'trimou': [r'trimou[\\/]', r'org\.trimou'],
    'handlebars.java': [r'handlebars\.java[\\/]', r'com\.github\.jknack\.handlebars'],
    'mustache.java': [r'mustache\.java[\\/]', r'com\.github\.mustachejava'],
    'jinja2.java': [r'jinja2\.java[\\/]', r'com\.hubspot\.jinjava'],
    'scalate': [r'scalate[\\/]', r'org\.fusesource\.scalate'],
    'play.templates': [r'play\.templates[\\/]', r'play\.templates\.Template'],
    'groovy.template': [r'groovy\.template[\\/]', r'groovy\.text'],
    'jamon': [r'jamon[\\/]', r'org\.jamon'],
    'knight': [r'knight[\\/]', r'com\.knight\.template'],
    'pug': [r'pug[\\/]', r'pug\.js', r'pug\.compile'],
    'ejs': [r'ejs[\\/]', r'ejs\.js', r'ejs\.compile'],
    'handlebars': [r'handlebars[\\/]', r'handlebars\.js', r'Handlebars\.SafeString', r'handlebars/dist/cjs/handlebars', r'Handlebars\.parse', r'handlebars/compiler/parser'],
    'mustache': [r'mustache[\\/]', r'mustache\.js', r'Mustache\.render'],
    'nunjucks': [r'nunjucks[\\/]', r'nunjucks\.Environment'],
    'dot': [r'dot[\\/]', r'doT\.js', r'dot\.template'],
    'liquidjs': [r'liquidjs[\\/]', r'liquidjs\.engine'],
    'marko': [r'marko[\\/]', r'marko-js', r'marko\.compile'],
    'hogan.js': [r'hogan\.js[\\/]', r'Hogan\.Template'],
    'haml': [r'haml[\\/]', r'haml-js', r'haml\.compile'],
    'slim': [r'slim[\\/]', r'slim-lang', r'slim\.js'],
    'eta': [r'eta[\\/]', r'eta\.js', r'eta\.compile'],
    'art-template': [r'art-template[\\/]', r'artTemplate'],
    'swig': [r'swig[\\/]', r'swig\.js', r'swig\.compile'],
    'dust': [r'dust[\\/]', r'dustjs', r'dust\.compile'],
    'ractive': [r'ractive[\\/]', r'ractive\.js'],
    'vue': [r'vue[\\/]', r'vue\.js', r'vue-template'],
    'angular': [r'angular[\\/]', r'angular\.js', r'ng-template'],
    'microtemplate': [r'microtemplate[\\/]', r'MicroTemplate'],
    'underscore': [r'underscore[\\/]', r'Underscore\.js', r'_.template'],
    'lodash': [r'lodash[\\/]', r'Lodash', r'_.template'],
    'jquery-tmpl': [r'jquery-tmpl[\\/]', r'jQuery\.tmpl'],
    'mustache-hogan': [r'mustache-hogan[\\/]', r'hogan\.mustache'],
    'bracket': [r'bracket[\\/]', r'bracket-template'],
    'whiskers': [r'whiskers[\\/]', r'whiskers\.js'],
    'plates': [r'plates[\\/]', r'Plates\.js'],
    't': [r't\.js[\\/]', r't\.Template'],
    'templayed': [r'templayed[\\/]', r'Templayed\.js'],
    'json-template': [r'json-template[\\/]', r'JSONTemplate'],
    'motemplate': [r'motemplate[\\/]', r'MOTemplate'],
    'scribe': [r'scribe[\\/]', r'Scribe\.js'],
    'erb': [r'erb[\\/]', r'ERB\.new', r'eRuby'],
    'haml': [r'haml[\\/]', r'Haml::Engine', r'haml-rails'],
    'slim': [r'slim[\\/]', r'Slim::Template', r'slim-lang'],
    'liquid': [r'liquid[\\/]', r'Liquid::Template', r'Liquid::Tag'],
    'mustache.rb': [r'mustache\.rb[\\/]', r'Mustache::Template'],
    'handlebars.rb': [r'handlebars\.rb[\\/]', r'Handlebars::Template'],
    'rabl': [r'rabl[\\/]', r'Rabl::Template'],
    'jbuilder': [r'jbuilder[\\/]', r'JbuilderTemplate'],
    'tilt': [r'tilt[\\/]', r'Tilt::Template'],
    'curly': [r'curly[\\/]', r'Curly::Template'],
    'radius': [r'radius[\\/]', r'Radius::Template'],
    'markaby': [r'markaby[\\/]', r'Markaby::Template'],
    'erubis': [r'erubis[\\/]', r'Erubis::Eruby'],
    'tenjin': [r'tenjin[\\/]', r'Tenjin::Template'],
    'mab': [r'mab[\\/]', r'Mab::Template'],
    'pongo2': [r'pongo2[\\/]', r'pongo2\.Template'],
    'jet': [r'jet[\\/]', r'jet\.Template'],
    'hero': [r'hero[\\/]', r'hero\.Template'],
    'quicktemplate': [r'quicktemplate[\\/]', r'quicktemplate\.qt'],
    'raymond': [r'raymond[\\/]', r'raymond\.Raymond'],
    'ego': [r'ego[\\/]', r'ego\.Template'],
    'templates': [r'templates[\\/]', r'html/template', r'text/template'],
    'ace': [r'ace[\\/]', r'ace\.Template', r'ace\.compile', r'ace\.render'],
    'amber': [r'amber[\\/]', r'amber\.Template'],
    'mustache.go': [r'mustache\.go[\\/]', r'mustache\.Render'],
    'handlebars.go': [r'handlebars\.go[\\/]', r'handlebars\.Render'],
    'liquid.go': [r'liquid\.go[\\/]', r'liquid\.Template'],
    'razor': [r'razor[\\/]', r'System\.Web\.Razor', r'RazorLight'],
    'scriban': [r'scriban[\\/]', r'scriban\.Template', r'Scriban\.TemplateContext'],
    'fluid': [r'fluid[\\/]', r'FluidTemplate'],
    'dotliquid': [r'dotliquid[\\/]', r'DotLiquid\.Template'],
    'handlebars.net': [r'handlebars\.net[\\/]', r'Handlebars\.Net'],
    'stubble': [r'stubble[\\/]', r'Stubble\.Template'],
    'nustache': [r'nustache[\\/]', r'Nustache\.Core'],
    'mustache.sharp': [r'mustache\.sharp[\\/]', r'MustacheSharp'],
    'spark': [r'spark[\\/]', r'SparkView', r'SparkEngine'],
    'nhaml': [r'nhaml[\\/]', r'NHaml\.Template'],
    'brail': [r'brail[\\/]', r'BrailTemplate'],
    'sharp_templ': [r'sharp_templ[\\/]', r'SharpTempl'],
    'liquid.net': [r'liquid\.net[\\/]', r'Liquid\.NET'],
    'inja': [r'inja[\\/]', r'inja::Template'],
    'jinja2cpp': [r'jinja2cpp[\\/]', r'jinja2::Template'],
    'mstch': [r'mstch[\\/]', r'mstch::template'],
    'qentem': [r'qentem[\\/]', r'qentem\.Template'],
    'teng_cpp': [r'teng[\\/]', r'teng::Template'],
    'ctemplate': [r'ctemplate[\\/]', r'ctemplate\.Template'],
    'mustache.cpp': [r'mustache\.cpp[\\/]', r'mustache::Render'],
    'fmt': [r'fmt[\\/]', r'fmt::format'],
    'pugic': [r'pugic[\\/]', r'Pugic'],
    'kainjow': [r'kainjow[\\/]', r'Kainjow'],
    'template-toolkit': [r'template-toolkit[\\/]', r'Template::Toolkit', r'Template\.pm'],
    'mason': [r'mason[\\/]', r'HTML::Mason', r'Mason::Interp'],
    'html-template': [r'html-template[\\/]', r'HTML::Template'],
    'text-template': [r'text-template[\\/]', r'Text::Template'],
    'template-perl': [r'template-perl[\\/]', r'Template::Perl'],
    'template-stash': [r'template-stash[\\/]', r'Template::Stash'],
    'open-power-template': [r'open-power-template[\\/]', r'OpenPowerTemplate', r'OPTv2'],
    'apache-tapestry': [r'apache-tapestry[\\/]', r'org\.apache\.tapestry'],
    'velocity-tools': [r'velocity-tools[\\/]', r'org\.apache\.velocity\.tools'],
    'gsp': [r'gsp[\\/]', r'groovy\.server\.pages'],
    'ssp': [r'ssp[\\/]', r'Scala Server Pages'],
    'jtwig': [r'jtwig[\\/]', r'jtwig\.Template'],
    'jinjava': [r'jinjava[\\/]', r'com\.hubspot\.jinjava'],
    'chunk': [r'chunk[\\/]', r'chunk\.template'],
    'tnt': [r'tnt[\\/]', r'tnt\.template'],
    'stringloader': [r'stringloader[\\/]', r'StringLoader'],
    'phptal': [r'phptal[\\/]', r'PHPTAL_Template'],
    'django-jinja': [r'django-jinja[\\/]', r'DjangoJinja'],
    'coffee': [r'coffee[\\/]', r'CoffeeKup'],
    'dry': [r'dry[\\/]', r'dry\.template'],
    'walrus': [r'walrus[\\/]', r'walrus\.template'],
    'sqwig': [r'sqwig[\\/]', r'Sqwig'],
    'hogan': [r'hogan[\\/]', r'Hogan\.js'],
    'mu2': [r'mu2[\\/]', r'mu2\.compile'],
    'templayed': [r'templayed[\\/]', r'Templayed\.js'],
    'underscore': [r'underscore[\\/]', r'Underscore\.js'],
    'spacebars': [r'spacebars[\\/]', r'spacebars', r'meteor\.spacebars'],
    'blaze': [r'blaze[\\/]', r'blaze', r'meteor\.blaze'],
    'handlebars-objc': [r'handlebars-objc[\\/]', r'Handlebars\.objc'],
    'grust': [r'grust[\\/]', r'grust\.template'],
    'templ8': [r'templ8[\\/]', r'Templ8'],
    'tempest': [r'tempest[\\/]', r'tempest\.template'],
    'plates': [r'plates[\\/]', r'plates\.Template'],
    'soy': [r'soy[\\/]', r'soy\.Template', r'Closure Templates'],
}
